### ISSUE TITLE
Wismec Predator 228 Support

### ISSUE THREAD

**Issue by zDeadKings** [maelstrom2001/ArcticFox#256] opened 2017-04-05 20:27 UTC
Being these use the same chip, I almost assume AirticFox should work right outta the box. But before I brick my brand new mod would like conformation. Thanks for a great piece of work. Breathed new life into 1 of my fav mod the Cuboid.

**Comment by TBXin** [comment] 2017-04-05 20:30
#255 #252 #250 #249 #246 #234 #185

![](http://i.imgur.com/TSf1kTL.png)

**Comment by zDeadKings** [comment] 2017-04-05 23:59
Thanks did not see it was a work in progress. I assume you will post  when it is available correct?

**Comment by TBXin** [comment] 2017-04-06 08:36
Let it be open. I hope people will not create duplicates ^^

**Comment by leddhedd** [comment] 2017-04-06 14:25
is there an ETA on the predator build? are we looking at days or weeks or longer? just so i can keep my eye out :)

**Comment by TBXin** [comment] 2017-04-06 15:30
@leddhedd ETA is a next release ^^
We will publish release version as soon as possible, there are no specific deadlines.

**Comment by hunterj12** [comment] 2017-04-08 04:40
How's the temperature control with stainless steel on the predator + arctic fox vs an alien? I'm trying to find  a new mod that actually works well and I would love to get a predator.

**Comment by maelstrom2001** [comment] 2017-04-08 10:21
@hunterj12 I recommend to watch [Dirk Oberhaus review](https://youtu.be/XXh3PrihtoU?t=31m41s) on RX300 with ArcticFox. On any other box TC will work the same way, so you can draw conclusions.

**Comment by SimonFricker** [comment] 2017-04-10 08:49
+1

**Comment by ETPNV13** [comment] 2017-04-10 09:48
+1

**Comment by javak810i** [comment] 2017-04-10 15:44
Any news on the Arctic fox FW for the new Wismec Predator? Would really appreciate that ;)

**Comment by TheSpiritof69** [comment] 2017-04-10 15:49
@javak810i https://github.com/maelstrom2001/ArcticFox/wiki/Changelog

**Comment by javak810i** [comment] 2017-04-10 16:02
@TheSpiritof69 Was rather looking for an answer like this "We're hoping to bring you Wismec Predator support in the upcoming 10 days or in the next release." Or something like this ;). But thanks anyway.

**Comment by TheSpiritof69** [comment] 2017-04-10 16:08
@javak810i Questions for ETA in non-commcerical, private software projects will in 99% of cases be answered with "It's done when it's done.".

**Comment by maelstrom2001** [comment] 2017-04-10 16:10
@javak810i In the next release :) with Eleaf QC support, powerbank mode (aka reverse charging for all devices), brand new skin and more. Please be patient :)

**Comment by javak810i** [comment] 2017-04-10 16:59
@maelstrom2001 Cool! Will be looking super forward to that :)

**Comment by eruecco87** [comment] 2017-04-10 17:09
+1 on the need of predator support, just bought one and found the Arctic Fox firmware.

Looks cool, great job guys!

**Comment by eruecco87** [comment] 2017-04-13 20:38
@maelstrom2001 I just uploaded the firmware to an Eleaf Aster, and I love it. This post is not to pressure a release but to let you guys know that Predator support will be highly appreciated.

Kudos again on the job

**Comment by hunterj12** [comment] 2017-04-19 19:16
Any chance the predator firmware will be released in April?

**Comment by TheSpiritof69** [comment] 2017-04-19 19:34
Everytime someone asks, the release will be pushed back 2 days. ⚡️

**Comment by javak810i** [comment] 2017-04-20 20:59
My Predator arrives on next week, so the Update will obviously be released next week :D
I wish :D.

**Comment by leddhedd** [comment] 2017-04-22 15:20
i can see that the readme has been updated to show support for the predator, is the new update imminent?

**Comment by hawkeyexp** [comment] 2017-04-22 18:50
Today it get my predator and noticed what good job the arctic firmware does :-) I Miss it :-)

**Comment by javak810i** [comment] 2017-04-25 21:42
Today I too joined the club of Predator owners :D. 
Super excited for the next release :)

**Comment by mumpen** [comment] 2017-04-26 11:25
Every day I come here and hope for the Predator support. 
You're doing a great job, hope we get the new version soon! 
<3

**Comment by hawkeyexp** [comment] 2017-05-04 09:22
Hi guys, can you give us some look inside the current state of dev ? Caused by the continious updates of upcoming readme it seems you make good progress...

**Comment by maelstrom2001** [comment] 2017-05-08 18:25
Released.

**Closed by maelstrom2001** 2017-05-08 18:25 UTC
Labels: Duplicate, Work In Progress
